[project]
name = "spotty"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.1.0",
    "pylint>=4.0.2",
    "rich>=13.7.0",
    "typer>=0.9.0",
]
